// <auto-generated />
using System;
using Airtickets.Data;
using Airtickets.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airtickets.Migrations
{
    [DbContext(typeof(AirTicketsDBContext))]
    partial class AirTicketsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "segment_status", new[] { "waiting", "refunded", "realized" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airtickets.Models.Segment", b =>
                {
                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.Property<int>("FlightNum")
                        .HasColumnType("integer");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ArriveDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArrivePlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DepartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OperationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PnrId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer");

                    b.Property<SegmentStatus>("Status")
                        .HasColumnType("segment_status");

                    b.HasKey("TicketNumber", "FlightNum");

                    b.HasIndex("TicketNumber", "SerialNumber")
                        .IsUnique();

                    b.ToTable("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
